
GET http://localhost:5000/api/khaibao/form


###

//lấy tất cả form trong 1 ngày xác định. nhập ngày như dưới theo name của enterprise và mail
GET http://localhost:5000/enterprise/getSpecificDay/2021-07-17?email=nhatlam1695@gmail.com


###

//lấy tất cả form trong 1 ngày xác định. nhập ngày như dưới theo name của enterprise. Only for excel
GET http://localhost:5000/enterprise/getSpecificDayForExcel/2021-07-17?enterpriseName=CÔNG


###

//get data for report page with enterprise name like below.
GET http://localhost:5000/enterprise/getReport?enterpriseName=CÔNG TY


###

//get data for report page with enterprise name like below. Only for excel
GET http://localhost:5000/enterprise/getReportForExcel?enterpriseName=CÔNG TY


###

//chọn user theo mail hoặc doanh nghiệp. filter => ?email=tên, ?enterpriseName=tên
GET http://localhost:5000/home/getAllEmail?email=la


###

//chọn enterprise theo mail. filter => ?email=tên
GET http://localhost:5000/enterprise/getAllEnterprise


###

//Update nhân viên theo id, ko dc để miền status 1 mình, nếu ko ếu chạy
PUT  http://localhost:5000/enterprise/editstaff/60eea912c96a4a15ac7f3df5
Content-Type: application/json

{
    "status": true,
    "department": "Chủ tịch",
    "phone": "65413215"
}

###

//Verify user theo id. phải có miền email, nếu ko éo chạy
PUT http://localhost:5000/home/verification/60f1cfbc92660542241977a3
Content-Type: application/json

{
    "status": true,
    "email": "sept9th2015@gmail.com"
}

###

//đếm form dựa vào mail
GET http://localhost:5000/api/khaibao/form/count?email=nhatlam1695@gmail.com


###

//lấy form cuối cùng. ?email để lấy form cuối theo email
GET http://localhost:5000/api/khaibao/form/lastform

###

//lấy tất cả form trong ngày. có thể sort theo mail => ?email=mail
GET http://localhost:5000/api/khaibao/form/getAllFormToday?email=ltv.9a2.21@gmail.com


###

POST http://localhost:5000/api/khaibao
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY1Mjc4NWMxMDQ4NzMwYWNlNmI2NjEiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiaWF0IjoxNjI2NzA5MzUwLCJleHAiOjE2MjY3MTExNTB9.Yc214IU5p0Ldh9l6_GlGhnyyL7eoGjd99cBguOTepxE


{
    "department": "abc",
    "phone": "8521555",
    "quest4": "Ho khan hoặc đau họng, Đau ngực hoặc khó thở",
    "quest5": "Test",
    "quest6": "Không",
    "quest7": "Không"
}

###

POST http://localhost:5000/home/register
Content-Type: application/json

{
    "email": "ltv.9a2.21@gmail.com"
}

###

//login để khai báo đối với user thường và để coi report đối với enterprise
POST http://localhost:5000/home/login
Content-Type: application/json

{
    "email": "ltv.9a2.21@gmail.com"
}

###

//login của enterprise
POST http://localhost:5000/enterprise/login
Content-Type: application/json

{
    "email": "sept9th2015@gmail.com"
}

###

//login để khai báo đối với user thường và để coi report đối với enterprise
POST http://localhost:5000/enterprise/pre-register
Content-Type: application/json

{
    "email": "nmman06@gmail.com"
}

###

//Add staff into DB with enterprise ID + name
POST http://localhost:5000/enterprise/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbnRlcnByaXNlSWQiOiI2MGVkNWI2YzdkOGU0ODI0MGM2NWY4ZDAiLCJlbWFpbCI6ImxvbmduaDIwMDcyMDAwQGdtYWlsLmNvbSIsIm5hbWUiOiJGUFQgU29mdHdhcmUiLCJpYXQiOjE2MjYyNTM1NDAsImV4cCI6MTYyNjI1NTM0MH0.hbvIrVKN1ab-ZOTF4OpWNuejqH2iDPCimZBAMZ_rYtw

{
    "email": "hnka301220@gmail.com",
    "department": "CEO",
    "phone": "0123456789"
}

###

//enterprise register
POST http://localhost:5000/enterprise/register
Content-Type: application/json

{
    "name": "Công Ty SUPA",
    "email": "nmman06@gmail.com",
    "address": "302 Dĩ An, Bình DƯơng, TP.HCM",
    "MST": "201258232",
    "document": ""
}

###

POST http://localhost:5000/home/activation
Content-Type: application/json

{
    "accessToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY1Mjc4NWMxMDQ4NzMwYWNlNmI2NjEiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiaWF0IjoxNjI2NzA5MzUwLCJleHAiOjE2MjY3MTExNTB9.Yc214IU5p0Ldh9l6_GlGhnyyL7eoGjd99cBguOTepxE"
}